# B042: Remember to call super().__init__() in custom exceptions initalizer.

## See Also

* [Bugbear B042](https://github.com/PyCQA/flake8-bugbear?tab=readme-ov-file)
